### ISSUE TITLE
Question: Accessing data with TaggedIndex

### ISSUE THREAD

**Issue by mr-mobster** [dist1ll/osmium#2]
How would one go about getting the data out of the AOVA structure? Inserting gives me a tagged index, how can I use this index to get back an enum in a type-safe way? Does Zig offer a way to construct tope-safe tagged value at runtime?

**Comment by dist1ll** [comment]
Yes, you can use [`@unionInit`](https://ziglang.org/documentation/0.11.0/#unionInit) for this. I've added a `.get()` implementation you can take a look at. For convenience I'm using an inline-for, but this should really be done with a lookup table instead.

**Comment by mr-mobster** [comment]
Very nice, thank you!
